### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by ed-snodgrass** [opennebraska/renters-help#18]
contact Danni for the Spanish translations 

Create the translation.

**Comment by ed-snodgrass** [comment]
This is what we need translated.        

        checkAllThatApply: 'Check all that apply',
        next: 'Next',
        no: 'No',
        noneOfTheAbove: 'None of the above',
        previous: 'Previous',
        yes: 'Yes',
        affordRentTitle: 'Can you afford your rent?',
        affordRentOptionLostSubstantialIncome: 'My household lost substantial income',
        affordRentOptionLostJob: 'I lost my job',
        affordRentOptionHoursCut: 'My hours were cut',
        affordRentOptionSalaryReduced: 'My salary was reduced',
        affordRentOptionExtraordinaryMedicalCost: 'I have extraordinary medical costs that I pay out of pocket that insurance does not cover',
        affordRentExtraordinaryExplained: 'An “extraordinary” medical expense is any un-reimbursed medical expense likely to exceed ' +
            '7.5% of one’s adjusted gross income for the year.',
        affordRentExtraordinaryQuestion: 'What are "extraordinary medical costs"?',
        attemptingToPayTitle: 'I am doing my best to pay as much rent as I can, given my circumstances',
        failedQualificationTitle: 'Sorry, it looks like you don\'t qualify',
        failedQualificationBody: 'If the answers you gave indicate you don\'t qualify, you can restart but please proceed with caution and ' +
            'remember that you must answer these questions truthfully. You could be subject to civil or criminal ' +
            'penalties if you lie on these forms. If you are in need of legal help, please see the resources provided ' +
            'by a legal aid organization: ',
        governmentHelpTitle: 'Did you do your best to get government help to pay the rent?',
        governmentHelpBody: 'If you do not qualify for any help from the government, or if applications were closed, your application ' +
            'was wait-listed, or assistance programs were no longer available or if you applied and you were denied, ' +
            'answer ‘Yes’.',
        governmentHelpBestEffortsQuestion: 'What are "best efforts" and "government help"?',
        governmentHelpBestEffortsExplanation: '"Government help" means any governmental rental or housing payment benefits available to the individual ' +
            'or any household member. "Best efforts" is not defined by the Order. You should document whether your any applications were successful.',
        homeAboutHeader: 'About Nebraska Renters Help',
        homeAboutInfo: 'Nebraska Renters Help was built by Code for Nebraska. ' +
            'The purpose of the site is to provide self-help tools and resources so struggling ' +
            'Nebraska renters can obtain entitled protection under the current ' +
            'CDC Federal Eviction Moratorium. The information in Nebraska Renters Help does not constitute legal ' +
            'advice and must not be used as a substitute for the advice of a lawyer qualified to give advice ' +
            'on legal issues pertaining to housing. We can help direct you to free legal services if ' +
            'necessary.',
        homeContactLegalAid: 'Please call <1>Legal Aid</1> toll-free at 1-844-268-5627',
        homeInstruction1Title: 'Fill out the form in 5 minutes',
        homeInstruction1Info: 'Answer a few questions and provide your<1/>landlord\'s contact information',
        homeInstruction2Title: 'The tool will create a letter',
        homeInstruction2Info: 'The app will create a letter that is ready<1/>to send based on your answers',
        homeInstruction3Title: 'Send the letter to your landlord',
        homeInstruction3Info: 'Download or print the letter to<1/>send to your landlord',
        homeLanguagePreference: 'Prefer English?',
        homeOtherRentalAssistance: 'Other Rental Assistance',
        homePageTitle: 'Are you facing an <1>eviction</1>? This tool can help.',
        homeReasonToUse: "If you're having trouble keeping up with your rent payments, the Federal Government has issued an " +
            "order that prevents " +
            "landlords in the US from evicting many of their tenants until after December 31, 2020. Use this " +
            "tool to see if you are covered, " +
            "and to produce the right letter (called a \"Declaration\") to send to your landlord, as required " +
            "by the order.",
        homeStartButton: 'Start Free Tool',
        incomeQualificationsTitle: 'Income Qualification',
        incomeQualificationsOptionNoIncome: 'I did not report any income to the I.R.S. for 2019',
        incomeQualificationsOptionStimulusCheck: 'I got a stimulus check (Economic Impact Payment) in 2020',
        incomeQualificationsOptionUnderIncomeThreshold: 'I either expect to earn no more than $99,000 in annual income for calendar year 2020 or no more than $198,000 if filing a joint tax return',
        landlordInfoTitle: 'Enter your landlord\'s information',
        landlordInfoBody: 'This information will determine where your letter is sent. You can send this information to go ' +
            'to your landlord, the owner of the property where you live, or another person who has the right ' +
            'to have you evicted or removed from where you live. If you are unsure where to send this notice, ' +
            'please look at your lease or ask your landlord where you may send a legal notice.',
        personalInformationTitle: 'Enter your information',
        personalInformationBody: 'We need this information to complete a cover letter to your landlord as well as to ensure that you qualify to use this self-help tool.',
        personalInformationFirstName: 'First Name',
        personalInformationLastName: 'Last Name',
        personalInformationAddress: 'Current Address',
        personalInformationUnit: 'Unit (optional)',
        personalInformationCity: 'City',
        personalInformationState: 'State',
        personalInformationZip: 'Zip',
        qualifiedTitle: 'Great, you qualify! Read the following information carefully.',
        qualifiedBodyAgreeingDescription: 'When you sign the Declaration form, you are agreeing that you understand the following sentences and ' +
            'that they are true:',
        qualifiedBodyProtected: 'Even though I am protected from eviction through December 31, 2020,',
        qualifiedBodyAgreeingStillResponsible: 'I still am responsible to pay my rent and follow all other rules of my lease. My landlord may charge me fees or interest.',
        qualifiedBodyAgreeingPayInFullAfterDate: 'After December 31, 2020, I may be required to pay all of the rent due, in full.',
        qualifiedBodyAgreeingTellTheTruth: 'I need to tell the truth on this form. If I do not, I may face civil or criminal penalties.',
        qualifiedBodyConfirmUnderstanding: 'I Understand',
        startTitle: 'How to stay in your home',
        startDescription: 'The federal government has banned landlords from evicting qualifying tenants for non-payment of ' +
            'rent due to the COVID-19 public health crisis. In order to protect yourself you need to:',
        startFirstStep: 'Make sure you qualify (there are 5 question we will ask you).',
        startSecondStep: 'Fill out your address and your landlord\'s information.',
        startThirdStep: 'Send the letter to your landlord (we can help you with that).',
        unsafeLivingTitle: 'Would an eviction result in a health risk to you by placing you in unsafe living conditions?',
        unsafeLivingOptionLikelyBecomeHomeless:'I am likely to become homeless',
        unsafeLivingOptionMoveToShelter:'I will probably need to move into a homeless shelter',
        unsafeLivingOptionMoveToCloseQuarters:'I will probably need to move in with someone else in close quarters',
        unsafeLivingOptionNoOtherSafeChoices:'I do not have any other safe housing choices',
        unsafeLivingOptionOtherChoicesMoreExpensive:'Any other safe housing choices would cost me more money',
        unsafeLivingOptionNotAtRisk:'I am not at risk of unsafe housing',

**Comment by ed-snodgrass** [comment]
https://docs.google.com/document/d/16ebR4J52VZe1nrL5y-vXz9Qf92xA92basGDGHMy9664/edit

**Comment by dodgees** [comment]
@eis95 Is there more to do with this, or should the issue be closed?
