### ISSUE TITLE
PDF download only triggered when clicking text, not the entire button

### ISSUE THREAD

**Issue by dodgees** [opennebraska/renters-help#21]
As the title indicates, the download is only triggered when clicking the text and not other parts of the button. This is especially painful because the button gives the normal material-ui feedback if you click another part of the button, but without triggering the download.

**Comment by ronaldewatts** [comment]
https://github.com/opennebraska/renters-help/commit/c172eb30bba48bb492a4c955587d1cd9e127b61a

Just switched around the `Button` and `PDFDownloadLink` elements.
